#!/bin/bash
grunt bump:minor full-compile compress || exit
scp LapisAzurai.zip 192.254.186.53:LapisAzurai.zip
echo "Unpacking..."
ssh 192.254.186.53 "cd LapisAzurai && rm -rf * && mv ../LapisAzurai.zip . && unzip -q LapisAzurai.zip"
echo "Deployed."
