#!/bin/bash
grunt full-compile
scp LapisAzurai.zip 192.254.186.53:LapisAzurai.zip
scp LapisAzuraiSFW.zip 192.254.186.53:LapisAzuraiSFW.zip
ssh 192.254.186.53 "cd LapisAzurai && rm -rf * && mv ../LapisAzurai.zip . && unzip -q LapisAzurai.zip"
ssh 192.254.186.53 "cd LapisAzuraiSFW && rm -rf * && mv ../LapisAzuraiSFW.zip LapisAzurai.zip && unzip -q LapisAzurai.zip"
